name: PolarPartyArea
version: 1
author: Hultberg
main: net.mittnett.edvin.area.PolarPartyArea.PolarPartyArea

commands:
    mod:
       description: Change a users access level
       usage: |
              /<command> [admin/mod/builder/guest] [target] 
    reloadConfig:
       description: Reload server config
       usage: |
              /<command>
    game:
       description: Game command, handle current game.
       usage: |
              /<command>
    compo:
       description: Compo command, set if allowing compo.
       usage: |
              /<command> [allow/disallow]
    who:
       description: Informasjon om en bruker eller deg selv.
       usage: |
              /<command> (brukernavn)
