name: PolarPartyArea
version: 1
author: Hultberg
main: net.mittnett.edvin.plugin.PolarPartyArea.PolarPartyArea

commands:
    mod:
       description: Change a users access level
       usage: |
              /<command> [admin/mod/builder/guest] [target] 
    gr:
       description: Groupsystem
       usage: |
              /<command> (options...)
    g:
       description: Gruppe chat
       usage: |
              /<command> [string]
