name: PolarPartyArea
version: 1
author: Hultberg
main: net.mittnett.edvin.area.PolarPartyArea.PolarPartyArea

commands:
    mod:
       description: Change a users access level
       usage: |
              /<command> [admin/mod/builder/guest] [target] 
    reloadConfig:
       description: Reload server config
       usage: |
              /<command>
    game:
       description: Game command, handle current game.
       usage: |
              /<command>
    compo:
       description: Compo command, set if allowing compo.
       usage: |
              /<command> [allow/disallow]
    who:
       description: Informasjon om en bruker eller deg selv.
       usage: |
              /<command> (brukernavn)
    kick:
       description: Kick a player.
       usage: |
              /<command> [username] [reason]
    ban:
       description: Ban a player, mode 0 requires admin access.
       usage: |
              /<command> [username] [mode(0/1/2)] [reason]
    unban:
       description: Unban a player banned on this server, will not unban global bans.
       usage: |
              /<command> [username]
    msg:
       description: Send en privat melding til en spiller.
       aliases: [pm, m]
       usage: |
              /<command> [to] [message]
    reply:
       description: Svar til personen som sist sendte deg en melding.
       aliases: [r]
       usage: |
              /<command> [message]
    listbans:
       description: Se ban information for user.
       aliases: [lb,bans]
       usage: |
              /<command> [user]
    spawn:
       description: Goto spawn
       usage: |
              /<command>
    tpall:
       description: Teleport all to you.
       usage: |
              /<command>
